---
title: 'STAT 443: Lab2'
author: 'Lai Wei (#31739014)'
date: "21 March, 2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#if you do not have the package, type install.packages("name_of_the_package")
library(knitr)
library(tseries)
```


```{r,echo=TRUE}
data(LakeHuron)
LakeHuron.train <- window(LakeHuron,start=1875,end=1967)
LakeHuron.test <- window(LakeHuron,start=1968,end=1972)
```

1.
```{r,echo=TRUE}
plot(LakeHuron.train,xlab="Year",ylab="Annual Level of Lake Huron")
acf(LakeHuron.train)
pacf(LakeHuron.train)

#pacf cuts off at lag 2 and acf decays, indicating AR(2) model.
```
2.
```{r,echo=TRUE}
fit<-arima(LakeHuron.train,order=c(2,0,0),include.mean = T)
fit
#fitted model:
```
$$ X_t-  578.9888= 1.0627*(X_{t-1}- 578.9888)-0.2691*(X_{t-2}- 578.9888) +Z_t $$
3.
```{r,echo=TRUE}
res<-residuals(fit)
acf(res)
#acf of residuals shows that no significant auto correlation after lag 0
tsdiag(fit)
#nearly all acf are located in the confidence boundary, that is, acf is small, and P-value is large enough, indicates that fitted model is good.
```
4.
```{r,echo=TRUE}
#use the predict command in R to forecast the Lake Huron level for the next three years,i.e., 1968, 1969, and 1970. Provide 95% prediction intervals for each forecast.

pre<-predict(fit,n.ahead = 3,se.fit=T)
pre$pred
#the prediction of 1968,1969,1970 are respectively 578.6940 , 578.8394 , 578.9093
upr<-pre$pred+1.96*pre$se
upr
#the upper level of 1968,1969,1970 are respectively 580.0540 , 580.8239 , 581.2131
lwr<-pre$pred-1.96*pre$se
lwr
#the lower level of 1968,1969,1970 are respectively 577.3340 , 576.8548 , 576.6056
```

5.
```{r,echo=TRUE}
LakeHuron.test[1:3]
#all three years prediction intervals contain the true value
```

